import turtle
turtle.Screen().bgcolor("purple")
Sc=turtle.Screen()
Sc.setup(400,300)
turtle.title("welcome to turtle screen")
turtle.Screen().bgcolor("red")
board=turtle.Turtle()
board.pencolor("orange")
board.forward(100)
board.left(120)
board.forward(100)
board.left(120)
board.forward(100)
turtle.done()